spring:
  banner:
    location: classpath:banner/employeesBanner.txt
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: EMPLOYEE-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://educc0r:laia200619@sgiem-cluster.ghx2esb.mongodb.net/empsgiem
#      uri: mongodb://localhost:27017/empsgiem

eureka:
  client:
    service-url:
      defaultZone : https://ms-sgiem-eureka.azurewebsites.net/eureka/

blob:
  connection-string: DefaultEndpointsProtocol=https;AccountName=sgiemstorage;AccountKey=almqBBmQJTs5bka5tHQ+5EJQ0arVia0TjjfgKhmtRTXR7CYAqoLhndJhQ8TAyp2FOajtpMOSEvgk+AStQtGZ1A==;EndpointSuffix=core.windows.net
  container-name: sgiemcontainer

azure:
  application-insights:
    instrumentation-key: 631ab52d-4f78-4668-868e-38bffd11755d
    logger:
      level: trace
    channel:
      in-process:
        developer-mode: true

server:
  port: 8081